space_string = ":svn_asset:"
fill_string = ":grammar:"

def create_message(message):    
    letters_collected = []
    for char in message.lower():
        if char in letters.keys():
            letters_collected.append(letters[char])
    result = ["", "", "", "", ""]
    for letter in letters_collected:
        for i in range(5):
            result[i] += (letter[i] + space_string)
    for line in result:
        print(line)

letters = {"a": [space_string + fill_string + space_string,
             fill_string + space_string + fill_string,
             fill_string * 3,
             fill_string + space_string + fill_string,
             fill_string + space_string + fill_string],
           "b": [fill_string * 2 + space_string,
             fill_string + space_string + fill_string,
             fill_string * 2 + space_string,
             fill_string + space_string + fill_string,
             fill_string * 2 + space_string],
           "c": [fill_string * 3,
             fill_string + space_string * 2,
             fill_string + space_string * 2,
             fill_string + space_string * 2,
             fill_string * 3],
           "d": [fill_string * 2 + space_string,
             fill_string + space_string + fill_string,
             fill_string + space_string + fill_string,
             fill_string + space_string + fill_string,
             fill_string * 3],
           "e":[fill_string * 3,
             fill_string + space_string * 2,
             fill_string * 3,
             fill_string + space_string * 2,
             fill_string * 3],
           "f": [fill_string * 3,
             fill_string + space_string * 2,
             fill_string * 3,
             fill_string + space_string * 2,
             fill_string + space_string * 2],
           "g": [fill_string * 4,
             fill_string + space_string * 3,
             fill_string + space_string + fill_string * 2,
             fill_string + space_string * 2 + fill_string,
             fill_string * 4],
           "h": [fill_string + space_string + fill_string,
             fill_string + space_string + fill_string,
             fill_string * 3,
             fill_string + space_string + fill_string,
             fill_string + space_string + fill_string],
           "i": [fill_string * 3,
             space_string + fill_string + space_string,
             space_string + fill_string + space_string,
             space_string + fill_string + space_string,
             fill_string * 3],
           "j": [space_string * 2 + fill_string,
             space_string * 2 + fill_string,
             space_string * 2 + fill_string,
             fill_string + space_string + fill_string,
             fill_string * 3],
           "k": [fill_string + space_string * 2 + fill_string,
             fill_string + space_string + fill_string + space_string,
             fill_string * 2 + space_string * 2,
             fill_string + space_string + fill_string + space_string,
             fill_string + space_string * 2 + fill_string],
           "l": [fill_string + space_string * 2,
             fill_string + space_string * 2,
             fill_string + space_string * 2,
             fill_string + space_string * 2,
             fill_string * 3],
           "m": [fill_string + space_string * 3 + fill_string,
             fill_string * 2 + space_string + fill_string * 2,
             fill_string + space_string + fill_string + space_string + fill_string,
             fill_string + space_string * 3 + fill_string,
             fill_string + space_string * 3 + fill_string],
           "n": [fill_string + space_string * 2 + fill_string,
             fill_string * 2 + space_string + fill_string,
             fill_string + space_string + fill_string + fill_string,
             fill_string + space_string * 2 + fill_string,
             fill_string + space_string * 2 + fill_string],
           "o": [fill_string * 3,
             fill_string + space_string + fill_string,
             fill_string + space_string + fill_string,
             fill_string + space_string + fill_string,
             fill_string * 3],
           "p": [fill_string * 3,
             fill_string + space_string + fill_string,
             fill_string * 3,
             fill_string + space_string * 2,
             fill_string + space_string * 2],
           "q": [fill_string * 4 + space_string,
             fill_string + space_string * 2 + fill_string + space_string,
             fill_string + space_string * 2 + fill_string + space_string,
             fill_string + space_string * 2 + fill_string + space_string,
             fill_string * 5],
           "r": [fill_string * 2 + space_string * 2,
             fill_string + space_string + fill_string + space_string,
             fill_string * 2 + space_string * 2,
             fill_string + space_string + fill_string + space_string,
             fill_string + space_string * 2 + fill_string],
           "s": [fill_string * 3,
             fill_string + space_string * 2,
             fill_string * 3,
             space_string * 2 + fill_string,
             fill_string * 3],
           "t": [fill_string * 3,
             space_string + fill_string + space_string,
             space_string + fill_string + space_string,
             space_string + fill_string + space_string,
             space_string + fill_string + space_string],
           "u": [fill_string + space_string + fill_string,
             fill_string + space_string + fill_string,
             fill_string + space_string + fill_string,
             fill_string + space_string + fill_string,
             fill_string * 3],
           "v": [fill_string + space_string + fill_string,
             fill_string + space_string + fill_string,
             fill_string + space_string + fill_string,
             fill_string + space_string + fill_string,
             space_string + fill_string + space_string],
           "w": [fill_string + space_string * 3 + fill_string,
             fill_string + space_string * 3 + fill_string,
             fill_string + space_string + fill_string + space_string + fill_string,
             fill_string + space_string + fill_string + space_string + fill_string,
             space_string + fill_string + space_string + fill_string + space_string],
           "x": [fill_string + space_string * 3 + fill_string,
             space_string + fill_string + space_string + fill_string + space_string,
             space_string * 2 + fill_string + space_string * 2,
             space_string + fill_string + space_string + fill_string + space_string,
             fill_string + space_string * 3 + fill_string],
           "y": [fill_string + space_string * 3 + fill_string,
             space_string + fill_string + space_string + fill_string + space_string,
             space_string * 2 + fill_string + space_string * 2,
             space_string * 2 + fill_string + space_string * 2,
             space_string * 2 + fill_string + space_string * 2],
           "z": [fill_string * 5,
             space_string * 3 + fill_string + space_string,
             space_string * 2 + fill_string + space_string * 2,
             space_string + fill_string + space_string * 3,
             fill_string * 5],
           " ": [space_string,
                 space_string,
                 space_string,
                 space_string,
                 space_string]
           }

create_message("to feel down")

